name: "Sanity checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sanity:
    name: "build and test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    steps:
      - name: "install golang"
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: "checkout code"
        uses: actions/checkout@v4.1.1
      - name: "build appliation"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}
          go build -o build/psfv
          build/psfv --help
          build/psfv version
